import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <html>

    <body>
      <header>
          <div class="header-box">
            <h1>Design thinking engineering project Group: 5 </h1>
            <p> </p>
          </div>
          <div class="top-box">
              <h2>Bodhi</h2>
          </div>
      </header>
          <div class="middle-box">
            <h2>Camera</h2>
            <p> </p>
        </div>
        <button id="camera-button"></button>
    </body>
    
  </html>
  )
}
